name: Event
version: '1.0-SNAPSHOT'
main: live.supeer.event.Event
api-version: '1.21'
authors: [ Supeeer ]
description: A dependency for other plugins, which handles the economy, among other things.
website: supeer.live
dependencies:
  server:
    FastAsyncWorldEdit:
      load: OMIT
      required: true
      join-classpath: true